-- MySQL Script generated by MySQL Workbench

-- Thu Nov 16 19:56:21 2023

-- Model: New Model    Version: 1.0

-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------

-- Schema cenco_db

-- -----------------------------------------------------

-- -----------------------------------------------------

-- Schema cenco_db

-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `cenco_db` DEFAULT CHARACTER SET utf8 ;

USE `cenco_db` ;

-- -----------------------------------------------------

-- Table `cenco_db`.`viviendas`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `cenco_db`.`viviendas` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `numero` VARCHAR(5) NOT NULL,
        `observaciones` VARCHAR(255) NULL,
        PRIMARY KEY (`id`),
        UNIQUE INDEX `viv_numero_UNIQUE` (`numero` ASC)
    ) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `cenco_db`.`personas`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `cenco_db`.`personas` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `viviendas_id` INT NOT NULL,
        `nombre` VARCHAR(255) NOT NULL,
        `apellido` VARCHAR(255) NOT NULL,
        `genero` ENUM("Hombre", "Mujer") NOT NULL,
        `cedula` VARCHAR(100) NULL,
        `telefono` VARCHAR(45) NULL,
        `fecha_nacimiento` DATE NOT NULL,
        `grado_instruccion` VARCHAR(255) NULL,
        `parentesco` VARCHAR(100) NULL,
        `es_jefe` TINYINT NOT NULL,
        PRIMARY KEY (`id`),
        UNIQUE INDEX `id_jefes_de_familia` (`id` ASC),
        UNIQUE INDEX `jefe_cedula` (`cedula` ASC),
        INDEX `fk_personas_viviendas1_idx` (`viviendas_id` ASC)
    ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------

-- Table `cenco_db`.`beneficios`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `cenco_db`.`beneficios` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `joseGregorio` TINYINT NOT NULL,
        `hogares` TINYINT NOT NULL,
        `lactante` TINYINT NOT NULL,
        `parto_humanizado` TINYINT NOT NULL,
        `amor_mayor` TINYINT NOT NULL,
        `inn` TINYINT NOT NULL,
        `personas_id` INT NOT NULL,
        PRIMARY KEY (`id`),
        UNIQUE INDEX `id_beneficios` (`id` ASC),
        INDEX `fk_beneficios_personas1_idx` (`personas_id` ASC)
    ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------

-- Table `cenco_db`.`carnets`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `cenco_db`.`carnets` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `patria_cod` INT NULL,
        `patria_ser` INT NULL,
        `psuv_cod` INT NULL,
        `psuv_ser` INT NULL,
        `personas_id` INT NOT NULL,
        PRIMARY KEY (`id`),
        UNIQUE INDEX `id_carnets` (`id` ASC),
        INDEX `fk_carnets_personas1_idx` (`personas_id` ASC)
    ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------

-- Table `cenco_db`.`enfermedades`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `cenco_db`.`enfermedades` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `nombre` VARCHAR(255) NOT NULL,
        PRIMARY KEY (`id`),
        UNIQUE INDEX `id_enfermedad` (`id` ASC)
    ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------

-- Table `cenco_db`.`medicamentos`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `cenco_db`.`medicamentos` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `nombre` VARCHAR(250) NOT NULL,
        PRIMARY KEY (`id`),
        UNIQUE INDEX `id_medicamento` (`id` ASC)
    ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------

-- Table `cenco_db`.`profesiones`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `cenco_db`.`profesiones` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `nombre` VARCHAR(100) NOT NULL,
        `prof_sector` ENUM('PUBLICO', 'PRIVADO') NOT NULL,
        PRIMARY KEY (`id`),
        UNIQUE INDEX `id_profesiones` (`id` ASC)
    ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------

-- Table `cenco_db`.`personas_has_profesiones`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `cenco_db`.`personas_has_profesiones` (
        `personas_id` INT NOT NULL,
        `profesiones_id` INT NOT NULL,
        INDEX `fk_personas_has_profesiones_profesiones1_idx` (`profesiones_id` ASC),
        INDEX `fk_personas_has_profesiones_personas1_idx` (`personas_id` ASC)
    ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------

-- Table `cenco_db`.`mascotas`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `cenco_db`.`mascotas` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `nombre` VARCHAR(255) NOT NULL,
        `genero` ENUM('MACHO', 'HEMBRA') NOT NULL,
        `viviendas_id` INT NOT NULL,
        PRIMARY KEY (`id`),
        INDEX `fk_mascotas_viviendas1_idx` (`viviendas_id` ASC)
    ) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `cenco_db`.`medicamentos_has_personas`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `cenco_db`.`medicamentos_has_personas` (
        `medicamentos_id` INT NOT NULL,
        `personas_id` INT NOT NULL,
        INDEX `fk_medicamentos_has_personas_personas1_idx` (`personas_id` ASC),
        INDEX `fk_medicamentos_has_personas_medicamentos1_idx` (`medicamentos_id` ASC)
    ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------

-- Table `cenco_db`.`ayudas_tecnicas`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `cenco_db`.`ayudas_tecnicas` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `nombre` VARCHAR(255) NOT NULL,
        PRIMARY KEY (`id`)
    ) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `cenco_db`.`personas_has_ayudas_tecnicas`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `cenco_db`.`personas_has_ayudas_tecnicas` (
        `personas_id` INT NOT NULL,
        `ayudas_tecnicas_id` INT NOT NULL,
        INDEX `fk_personas_has_ayudas_tecnicas_ayudas_tecnicas1_idx` (`ayudas_tecnicas_id` ASC),
        INDEX `fk_personas_has_ayudas_tecnicas_personas1_idx` (`personas_id` ASC)
    ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------

-- Table `cenco_db`.`centros_de_votaciones`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `cenco_db`.`centros_de_votaciones` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `nombre` VARCHAR(255) NOT NULL,
        PRIMARY KEY (`id`)
    ) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `cenco_db`.`personas_has_centros_de_votaciones`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `cenco_db`.`personas_has_centros_de_votaciones` (
        `personas_id` INT NOT NULL,
        `centros_de_votaciones_id` INT NOT NULL,
        PRIMARY KEY (
            `personas_id`,
            `centros_de_votaciones_id`
        ),
        INDEX `fk_personas_has_centros_de_votaciones_centros_de_votaciones_idx` (
            `centros_de_votaciones_id` ASC
        ),
        INDEX `fk_personas_has_centros_de_votaciones_personas1_idx` (`personas_id` ASC)
    ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------

-- Table `cenco_db`.`enfermedades_has_personas`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `cenco_db`.`enfermedades_has_personas` (
        `enfermedades_id` INT NOT NULL,
        `personas_id` INT NOT NULL,
        PRIMARY KEY (
            `enfermedades_id`,
            `personas_id`
        ),
        INDEX `fk_enfermedades_has_personas_personas1_idx` (`personas_id` ASC),
        INDEX `fk_enfermedades_has_personas_enfermedades1_idx` (`enfermedades_id` ASC)
    ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb3;